Repository Xabaril/Esquio, pull requests merged in 2019-09, with the labels that each got.

#48 Feature/ux improvements
  src/Esquio.UI/ClientApp/src/app/products/ProductsForm.vue
  src/Esquio.UI/ClientApp/src/app/products/flags/FlagsForm.vue
  src/Esquio.UI/ClientApp/src/app/products/flags/toggles/TogglesForm.vue
  src/Esquio.UI/ClientApp/src/app/shared/floating/FloatingSave.vue
  src/Esquio.UI/ClientApp/src/app/shared/floating/index.ts
  src/Esquio.UI/ClientApp/src/app/shared/input/Input-Text.vue
  src/Esquio.UI/ClientApp/src/app/shared/parameters/Parameter.vue
  src/Esquio.UI/ClientApp/src/app/shared/parameters/SemicolonParameter.vue
  src/Esquio.UI/ClientApp/src/app/shared/parameters/StringParameter.vue
Labels: UI

#51 Update Esquio 1.1 tasks
  ROADMAP.md
Labels: Documentation

#52 Created new HeaderValueToggle
  src/Esquio.AspNetCore/Toggles/ClaimValueToggle.cs
  src/Esquio.AspNetCore/Toggles/HeaderValueToggle.cs
  tests/UnitTests/Esquio.AspNetCore/Toggles/HeaderValueToggleTests.cs
Labels: ASP.NET CORE

#53 Features/typed diagnostic listener event data
  samples/WebApp/Startup.cs
  src/Esquio/DefaultFeatureService.cs
  src/Esquio/Diagnostics/EsquioDiagnostics.cs
  src/Esquio/Diagnostics/EsquioEventData.cs
Labels: Core
